# This file was generated by GoReleaser. DO NOT EDIT.
cask "tdu" do
  module GitHubPrivateRepo
    def self.token
      github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      raise "HOMEBREW_GITHUB_API_TOKEN is not set. See: brew info tdu" if github_token.nil? || github_token.empty?
      github_token
    end

    def self.release_asset_url(tag, name)
      require "json"
      require "net/http"
      require "uri"

      uri = URI.parse("https://api.github.com/repos/TD-Yofun/tdu-cli/releases/tags/#{tag}")
      resp = Net::HTTP.get(uri, {
        "Accept" => "application/vnd.github+json",
        "Authorization" => "Bearer #{token}",
        "X-GitHub-Api-Version" => "2022-11-28"
      })
      release = JSON.parse(resp)
      asset = release["assets"].find { |a| a["name"] == name }
      raise "Asset #{name} not found in release #{tag}" if asset.nil?
      asset["url"]
    end
  end

  name "tdu"
  desc "talkdesk utils - a collection of daily work utilities"
  homepage "https://github.com/TD-Yofun/tdu-cli"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tdu"

  on_macos do
    on_intel do
      url "#{GitHubPrivateRepo.release_asset_url("v#{version}", "tdu-cli_#{version}_darwin_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubPrivateRepo.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "4e0a787f267f903f76726f63f62c1f13ba2ed06a96017a872cfc46b687aea2bd"
    end
    on_arm do
      url "#{GitHubPrivateRepo.release_asset_url("v#{version}", "tdu-cli_#{version}_darwin_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubPrivateRepo.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "39479d8b56dab85b0644bc0129ef271a880e2765f9555b7e1ce4a1fcec4869f1"
    end
  end

  on_linux do
    on_intel do
      url "#{GitHubPrivateRepo.release_asset_url("v#{version}", "tdu-cli_#{version}_linux_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubPrivateRepo.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "f47ab3172a59b29fd16f1320873ddc6bfddb261448fb3530977e0c6b954a2dee"
    end
    on_arm do
      url "#{GitHubPrivateRepo.release_asset_url("v#{version}", "tdu-cli_#{version}_linux_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubPrivateRepo.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "b391de751e564cac1befa9d2d63baf20bd3cde1a01603d8d301b3a1889c7a5ef"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tdu"]
    end
  end

  caveats do
    "This cask downloads from a private GitHub repository."
    "You must set HOMEBREW_GITHUB_API_TOKEN in your shell profile:"
    ""
    "  export HOMEBREW_GITHUB_API_TOKEN=your_github_personal_access_token"
  end

  # No zap stanza required
end
