# This file was generated by GoReleaser. DO NOT EDIT.
cask "tdu" do
  module GitHubPrivateRepo
    def self.token
      github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      raise "HOMEBREW_GITHUB_API_TOKEN is not set. See: brew info tdu" if github_token.nil? || github_token.empty?
      github_token
    end

    def self.release_asset_url(tag, name)
      require "json"
      require "net/http"
      require "uri"

      uri = URI.parse("https://api.github.com/repos/TD-Yofun/tdu-cli/releases/tags/#{tag}")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      request = Net::HTTP::Get.new(uri)
      request["Accept"] = "application/vnd.github+json"
      request["Authorization"] = "Bearer #{token}"
      request["X-GitHub-Api-Version"] = "2022-11-28"
      response = http.request(request)
      release = JSON.parse(response.body)
      assets = release["assets"]
      raise "No assets found in release #{tag}. Check your HOMEBREW_GITHUB_API_TOKEN has access to TD-Yofun/tdu-cli." if assets.nil?
      asset = assets.find { |a| a["name"] == name }
      raise "Asset #{name} not found in release #{tag}" if asset.nil?
      asset["url"]
    end
  end

  name "tdu"
  desc "talkdesk utils - a collection of daily work utilities"
  homepage "https://github.com/TD-Yofun/tdu-cli"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tdu"

  on_macos do
    on_intel do
      url "#{GitHubPrivateRepo.release_asset_url("v#{version}", "tdu-cli_#{version}_darwin_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubPrivateRepo.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "e86903aba931978b7c0317508105de54becff9a7bd8b7e5d40a5da7980337a83"
    end
    on_arm do
      url "#{GitHubPrivateRepo.release_asset_url("v#{version}", "tdu-cli_#{version}_darwin_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubPrivateRepo.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "123dc1e88aa0895dffe0ea20d35dee8047a438040eff8712075c071dcdf60feb"
    end
  end

  on_linux do
    on_intel do
      url "#{GitHubPrivateRepo.release_asset_url("v#{version}", "tdu-cli_#{version}_linux_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubPrivateRepo.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "dd538f673bb48c1b9d91571aa6a66a67b0e09c1ec5629b38f5857c0548195cc8"
    end
    on_arm do
      url "#{GitHubPrivateRepo.release_asset_url("v#{version}", "tdu-cli_#{version}_linux_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubPrivateRepo.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
      sha256 "a8431bc2db737fc7494bdaa54149403e3fecc9c987a6aa8e4777429e7bad703e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tdu"]
    end
  end

  caveats do
    "This cask downloads from a private GitHub repository."
    "You must set HOMEBREW_GITHUB_API_TOKEN in your shell profile:"
    ""
    "  export HOMEBREW_GITHUB_API_TOKEN=your_github_personal_access_token"
  end

  # No zap stanza required
end
