# This file was generated by GoReleaser. DO NOT EDIT.
cask "tdu" do
  module GitHubPrivateRepo
    def self.token
      github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      raise "HOMEBREW_GITHUB_API_TOKEN is not set. See: brew info tdu" if github_token.nil? || github_token.empty?
      github_token
    end

    def self.release_asset_url(tag, name)
      require "json"
      require "net/http"
      require "uri"

      uri = URI.parse("https://api.github.com/repos/TD-Yofun/tdu-cli/releases/tags/#{tag}")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      request = Net::HTTP::Get.new(uri)
      request["Accept"] = "application/vnd.github+json"
      request["Authorization"] = "Bearer #{token}"
      request["X-GitHub-Api-Version"] = "2022-11-28"
      response = http.request(request)
      release = JSON.parse(response.body)
      assets = release["assets"]
      raise "No assets found in release #{tag}. Check your HOMEBREW_GITHUB_API_TOKEN has access to TD-Yofun/tdu-cli." if assets.nil?
      asset = assets.find { |a| a["name"] == name }
      raise "Asset #{name} not found in release #{tag}" if asset.nil?
      asset["url"]
    end
  end

  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "e84dcd3cec174b93572a2bbe0e3b2d6a02e69dd49b020e03914dc0320e57570c"
      url "#{GitHubPrivateRepo.release_asset_url("v#{version}", "tdu-cli_#{version}_darwin_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubPrivateRepo.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
    on_arm do
      sha256 "2590549cff0461216b14331a1fa2a06f57d9347c7b7d0483fee715e7f7bb519e"
      url "#{GitHubPrivateRepo.release_asset_url("v#{version}", "tdu-cli_#{version}_darwin_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubPrivateRepo.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
  end

  on_linux do
    on_intel do
      sha256 "3a50ce9f96d7874e02cce592df64f8076bc397121bfa57c660da02b5dbee046b"
      url "#{GitHubPrivateRepo.release_asset_url("v#{version}", "tdu-cli_#{version}_linux_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubPrivateRepo.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
    on_arm do
      sha256 "d4633d4175ec80428f418c8f66d7c9c8924945942374332c0411ebb72fd4d686"
      url "#{GitHubPrivateRepo.release_asset_url("v#{version}", "tdu-cli_#{version}_linux_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubPrivateRepo.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
  end

  name "tdu"
  desc "talkdesk utils - a collection of daily work utilities"
  homepage "https://github.com/TD-Yofun/tdu-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tdu"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tdu"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This cask downloads from a private GitHub repository.
    You must set HOMEBREW_GITHUB_API_TOKEN in your shell profile:

      export HOMEBREW_GITHUB_API_TOKEN=your_github_personal_access_token
  EOS
end
